#!/bin/bash
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
rojo="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
clear
echo -e "\033[41;1;37m VPS•BARBA               \033[0m"
sleep 1
echo -e "\033[44;1;37m Seleccione un Script:   \033[0m"
sleep 1.5s
echo -e "$cyan[1]$amarelo SCRIPT VPS-BARBA"
echo -e "$cyan[2]$amarelo MINER-BITCOIN"
echo -e "$cyan[3]$amarelo CHECKER PROXY"
echo -e "$cyan[4]$amarelo GENERADOR DE CC"
echo -e "$cyan[5]$amarelo CHECKER HOST"
echo -e "\033[0;32m=========================\033[0m"
read -p "OPCION: " utilitario

if [ "$utilitario" = "1" ]
then
clear
echo -e "\033[44;1;37m QUE VERSION DESEA      \033[0m"
sleep 1.5s
echo -e "$cyan[1]$amarelo Shell-Script (Recomendado)"
echo -e "$cyan[2]$amarelo Python "
echo -e "\033[0;32m=========================\033[0m"
read -p "OPCION: " versao
if [ "$versao" = "1" ]
then
sleep 1
echo -e "\033[44;1;37m Instalando....         \033[0m "
sleep 0.5s
echo -e "\033[44;1;37m Instalado con Exito!   \033[0m"
echo -e "$rojo Para Usar El Script  Asi:\n$verde menu\033[0m"
fi



if [ "$versao" = "2" ]
then
sleep 1
echo -e  "\033[44;1;37m Instalando....        \033[0m"

sleep 0.5s
echo -e  "\033[44;1;37m Instalado con Exito!  \033[0m"
echo -e "$rojo para usar el script asi:\n $verde menu\033[0m"
fi

fi
if [ "$utilitario" = "2" ]
then
sleep 1
echo -e "\033[44;1;37m Instalando....          \033[0m "
sleep 0.5s

echo -e "\033[44;1;37m Instalado con exito!    \033[0m "
echo -e "$rojo para usar el script asi:\n$verde sudo sh$verde miner.sh CARTEIRA BITCOIN\033[0m"
fi
if [ "$utilitario" = "3" ]
then
sleep 1
echo -e "\033[44;1;37m Instalando....          \033[0m "
sleep 0.5s

echo -e "\033[44;1;37m Instalado con Exito!	\033[0m "

echo -e "$rojo Para Usar El Script Asi:\n $verde sudo $verde proxy ARQUIVO/Ruta de Los Proxys \033[0m"
fi
if [ "$utilitario" = "4" ]
then
sleep 1
echo -e "\033[44;1;37m Instalando...		\033[0m "
sleep 0.5s

echo -e  "\033[44;1;37m Instalado con Exito!	\033[0m "

echo -e "$rojo Para Iniciar el Script Asi:\n$verde sudo $verde ccgen BIN NUMERO-DE-CCS 'SEPARADOR'"
fi
if [ "$utilitario" = "5" ]
then
sleep 1
echo -e "\033[44;1;37m Instalando....		\033[0m "
sleep 0.5s

echo -e  "\033[44;1;37m Instalado com Exito!	\033[0m "

echo -e "$rojo para  iniciar el script asi: \n $verde sudo  hosts \033[0m LISTA-COM-HOSTS"
fi

exit 0
